// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/tariff.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Web {

  /// <summary>Holder for reflection information generated from Protos/tariff.proto</summary>
  public static partial class TariffReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/tariff.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TariffReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90b3MvdGFyaWZmLnByb3RvEgZ0YXJpZmYaG2dvb2dsZS9wcm90b2J1",
            "Zi9lbXB0eS5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3Rv",
            "Ih4KEEdldFRhcmlmZlJlcXVlc3QSCgoCaWQYASABKAUixAIKC1RhcmlmZlJl",
            "cGx5EgoKAmlkGAEgASgFEg0KBXRpdGxlGAIgASgJEjEKC2Rlc2NyaXB0aW9u",
            "GAMgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEhkKEXR5cGVf",
            "b2ZfZmVlX2RlYml0GAQgASgJEhgKEHN1YnNjcmlwdGlvbl9mZWUYBSABKAUS",
            "FQoNbWludXRlc19saW1pdBgGIAEoBRIeChZpbnRlcm5ldF90cmFmZmljX2xp",
            "bWl0GAcgASgFEg0KBXByaWNlGAggASgFEjYKEGRhdGVfb2ZfY3JlYXRpb24Y",
            "CSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSNAoOZGF0ZV9v",
            "Zl91cGRhdGUYCiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUi",
            "NwoPVGFyaWZmTGlzdFJlcGx5EiQKB1RhcmlmZnMYASADKAsyEy50YXJpZmYu",
            "VGFyaWZmUmVwbHkyiwEKDVRhcmlmZlNlcnZpY2USPgoLTGlzdFRhcmlmZnMS",
            "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkaFy50YXJpZmYuVGFyaWZmTGlzdFJl",
            "cGx5EjoKCUdldFRhcmlmZhIYLnRhcmlmZi5HZXRUYXJpZmZSZXF1ZXN0GhMu",
            "dGFyaWZmLlRhcmlmZlJlcGx5QgaqAgNXZWJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Web.GetTariffRequest), global::Web.GetTariffRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Web.TariffReply), global::Web.TariffReply.Parser, new[]{ "Id", "Title", "Description", "TypeOfFeeDebit", "SubscriptionFee", "MinutesLimit", "InternetTrafficLimit", "Price", "DateOfCreation", "DateOfUpdate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Web.TariffListReply), global::Web.TariffListReply.Parser, new[]{ "Tariffs" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetTariffRequest : pb::IMessage<GetTariffRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetTariffRequest> _parser = new pb::MessageParser<GetTariffRequest>(() => new GetTariffRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetTariffRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Web.TariffReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTariffRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTariffRequest(GetTariffRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTariffRequest Clone() {
      return new GetTariffRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetTariffRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetTariffRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetTariffRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TariffReply : pb::IMessage<TariffReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TariffReply> _parser = new pb::MessageParser<TariffReply>(() => new TariffReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TariffReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Web.TariffReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffReply(TariffReply other) : this() {
      id_ = other.id_;
      title_ = other.title_;
      Description = other.Description;
      typeOfFeeDebit_ = other.typeOfFeeDebit_;
      subscriptionFee_ = other.subscriptionFee_;
      minutesLimit_ = other.minutesLimit_;
      internetTrafficLimit_ = other.internetTrafficLimit_;
      price_ = other.price_;
      DateOfCreation = other.DateOfCreation;
      DateOfUpdate = other.DateOfUpdate;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffReply Clone() {
      return new TariffReply(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_description_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string description_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = value;
      }
    }


    /// <summary>Field number for the "type_of_fee_debit" field.</summary>
    public const int TypeOfFeeDebitFieldNumber = 4;
    private string typeOfFeeDebit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TypeOfFeeDebit {
      get { return typeOfFeeDebit_; }
      set {
        typeOfFeeDebit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "subscription_fee" field.</summary>
    public const int SubscriptionFeeFieldNumber = 5;
    private int subscriptionFee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SubscriptionFee {
      get { return subscriptionFee_; }
      set {
        subscriptionFee_ = value;
      }
    }

    /// <summary>Field number for the "minutes_limit" field.</summary>
    public const int MinutesLimitFieldNumber = 6;
    private int minutesLimit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MinutesLimit {
      get { return minutesLimit_; }
      set {
        minutesLimit_ = value;
      }
    }

    /// <summary>Field number for the "internet_traffic_limit" field.</summary>
    public const int InternetTrafficLimitFieldNumber = 7;
    private int internetTrafficLimit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InternetTrafficLimit {
      get { return internetTrafficLimit_; }
      set {
        internetTrafficLimit_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 8;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "date_of_creation" field.</summary>
    public const int DateOfCreationFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _single_dateOfCreation_codec = pb::FieldCodec.ForClassWrapper<string>(74);
    private string dateOfCreation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateOfCreation {
      get { return dateOfCreation_; }
      set {
        dateOfCreation_ = value;
      }
    }


    /// <summary>Field number for the "date_of_update" field.</summary>
    public const int DateOfUpdateFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _single_dateOfUpdate_codec = pb::FieldCodec.ForClassWrapper<string>(82);
    private string dateOfUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateOfUpdate {
      get { return dateOfUpdate_; }
      set {
        dateOfUpdate_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TariffReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TariffReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Title != other.Title) return false;
      if (Description != other.Description) return false;
      if (TypeOfFeeDebit != other.TypeOfFeeDebit) return false;
      if (SubscriptionFee != other.SubscriptionFee) return false;
      if (MinutesLimit != other.MinutesLimit) return false;
      if (InternetTrafficLimit != other.InternetTrafficLimit) return false;
      if (Price != other.Price) return false;
      if (DateOfCreation != other.DateOfCreation) return false;
      if (DateOfUpdate != other.DateOfUpdate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (description_ != null) hash ^= Description.GetHashCode();
      if (TypeOfFeeDebit.Length != 0) hash ^= TypeOfFeeDebit.GetHashCode();
      if (SubscriptionFee != 0) hash ^= SubscriptionFee.GetHashCode();
      if (MinutesLimit != 0) hash ^= MinutesLimit.GetHashCode();
      if (InternetTrafficLimit != 0) hash ^= InternetTrafficLimit.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      if (dateOfCreation_ != null) hash ^= DateOfCreation.GetHashCode();
      if (dateOfUpdate_ != null) hash ^= DateOfUpdate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (description_ != null) {
        _single_description_codec.WriteTagAndValue(output, Description);
      }
      if (TypeOfFeeDebit.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TypeOfFeeDebit);
      }
      if (SubscriptionFee != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SubscriptionFee);
      }
      if (MinutesLimit != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MinutesLimit);
      }
      if (InternetTrafficLimit != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InternetTrafficLimit);
      }
      if (Price != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Price);
      }
      if (dateOfCreation_ != null) {
        _single_dateOfCreation_codec.WriteTagAndValue(output, DateOfCreation);
      }
      if (dateOfUpdate_ != null) {
        _single_dateOfUpdate_codec.WriteTagAndValue(output, DateOfUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (description_ != null) {
        _single_description_codec.WriteTagAndValue(ref output, Description);
      }
      if (TypeOfFeeDebit.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TypeOfFeeDebit);
      }
      if (SubscriptionFee != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SubscriptionFee);
      }
      if (MinutesLimit != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MinutesLimit);
      }
      if (InternetTrafficLimit != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InternetTrafficLimit);
      }
      if (Price != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Price);
      }
      if (dateOfCreation_ != null) {
        _single_dateOfCreation_codec.WriteTagAndValue(ref output, DateOfCreation);
      }
      if (dateOfUpdate_ != null) {
        _single_dateOfUpdate_codec.WriteTagAndValue(ref output, DateOfUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (description_ != null) {
        size += _single_description_codec.CalculateSizeWithTag(Description);
      }
      if (TypeOfFeeDebit.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TypeOfFeeDebit);
      }
      if (SubscriptionFee != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SubscriptionFee);
      }
      if (MinutesLimit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinutesLimit);
      }
      if (InternetTrafficLimit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InternetTrafficLimit);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      if (dateOfCreation_ != null) {
        size += _single_dateOfCreation_codec.CalculateSizeWithTag(DateOfCreation);
      }
      if (dateOfUpdate_ != null) {
        size += _single_dateOfUpdate_codec.CalculateSizeWithTag(DateOfUpdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TariffReply other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.description_ != null) {
        if (description_ == null || other.Description != "") {
          Description = other.Description;
        }
      }
      if (other.TypeOfFeeDebit.Length != 0) {
        TypeOfFeeDebit = other.TypeOfFeeDebit;
      }
      if (other.SubscriptionFee != 0) {
        SubscriptionFee = other.SubscriptionFee;
      }
      if (other.MinutesLimit != 0) {
        MinutesLimit = other.MinutesLimit;
      }
      if (other.InternetTrafficLimit != 0) {
        InternetTrafficLimit = other.InternetTrafficLimit;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      if (other.dateOfCreation_ != null) {
        if (dateOfCreation_ == null || other.DateOfCreation != "") {
          DateOfCreation = other.DateOfCreation;
        }
      }
      if (other.dateOfUpdate_ != null) {
        if (dateOfUpdate_ == null || other.DateOfUpdate != "") {
          DateOfUpdate = other.DateOfUpdate;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            string value = _single_description_codec.Read(input);
            if (description_ == null || value != "") {
              Description = value;
            }
            break;
          }
          case 34: {
            TypeOfFeeDebit = input.ReadString();
            break;
          }
          case 40: {
            SubscriptionFee = input.ReadInt32();
            break;
          }
          case 48: {
            MinutesLimit = input.ReadInt32();
            break;
          }
          case 56: {
            InternetTrafficLimit = input.ReadInt32();
            break;
          }
          case 64: {
            Price = input.ReadInt32();
            break;
          }
          case 74: {
            string value = _single_dateOfCreation_codec.Read(input);
            if (dateOfCreation_ == null || value != "") {
              DateOfCreation = value;
            }
            break;
          }
          case 82: {
            string value = _single_dateOfUpdate_codec.Read(input);
            if (dateOfUpdate_ == null || value != "") {
              DateOfUpdate = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            string value = _single_description_codec.Read(ref input);
            if (description_ == null || value != "") {
              Description = value;
            }
            break;
          }
          case 34: {
            TypeOfFeeDebit = input.ReadString();
            break;
          }
          case 40: {
            SubscriptionFee = input.ReadInt32();
            break;
          }
          case 48: {
            MinutesLimit = input.ReadInt32();
            break;
          }
          case 56: {
            InternetTrafficLimit = input.ReadInt32();
            break;
          }
          case 64: {
            Price = input.ReadInt32();
            break;
          }
          case 74: {
            string value = _single_dateOfCreation_codec.Read(ref input);
            if (dateOfCreation_ == null || value != "") {
              DateOfCreation = value;
            }
            break;
          }
          case 82: {
            string value = _single_dateOfUpdate_codec.Read(ref input);
            if (dateOfUpdate_ == null || value != "") {
              DateOfUpdate = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TariffListReply : pb::IMessage<TariffListReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TariffListReply> _parser = new pb::MessageParser<TariffListReply>(() => new TariffListReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TariffListReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Web.TariffReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffListReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffListReply(TariffListReply other) : this() {
      tariffs_ = other.tariffs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TariffListReply Clone() {
      return new TariffListReply(this);
    }

    /// <summary>Field number for the "Tariffs" field.</summary>
    public const int TariffsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Web.TariffReply> _repeated_tariffs_codec
        = pb::FieldCodec.ForMessage(10, global::Web.TariffReply.Parser);
    private readonly pbc::RepeatedField<global::Web.TariffReply> tariffs_ = new pbc::RepeatedField<global::Web.TariffReply>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Web.TariffReply> Tariffs {
      get { return tariffs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TariffListReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TariffListReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!tariffs_.Equals(other.tariffs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= tariffs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      tariffs_.WriteTo(output, _repeated_tariffs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      tariffs_.WriteTo(ref output, _repeated_tariffs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += tariffs_.CalculateSize(_repeated_tariffs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TariffListReply other) {
      if (other == null) {
        return;
      }
      tariffs_.Add(other.tariffs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            tariffs_.AddEntriesFrom(input, _repeated_tariffs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            tariffs_.AddEntriesFrom(ref input, _repeated_tariffs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
